version: '2'
services:
  db:
    image: mariadb:10.4
    labels:
      org.cookie.container: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data/database:/var/lib/mysql
  web: &app
    image: ubcctlt/mediawiki:REL1_35
    ports:
      - 8086:80
    # use the links section if you want to use a container for a database.
    # if not, and you want to use an external database server, configure
    # if with the environment variables in the 'environment' section.
    # see README.md for more details.
    links:
      - db
    labels:
      org.cookie.container: "mediawiki"
    # uncomment the 'volumes' section to enable a shared volume with docker-compose
    volumes:
      - ./data/web:/data:rw
      - ./data/config/CustomSettings.php:/conf/CustomSettings.php
      # do not uncomment this when starting a new instance from scratch as
      # init script won't be able to move this file
      #- ./data/config/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./data/config/CustomHooks.php:/var/www/html/CustomHooks.php
      # FIXME this is a custom change on Parsoid PHP implementation since mw 1.35.
      # the Parsoid domain is not configurable. so we needed to disable the check as we are using "localhost" in Restbase redirection
      - ./data/config/ParsoidHandler_custom_1_35.php:/var/www/html/vendor/wikimedia/parsoid/extension/src/Rest/Handler/ParsoidHandler.php
    environment:
      - PARSOID_DOMAIN=localhost
      - MEDIAWIKI_SITE_SERVER=https://cookiewiki.eientei.org
      - MEDIAWIKI_SITE_NAME=Cookie wiki
      - MEDIAWIKI_DB_HOST=db
      - MEDIAWIKI_DB_PASSWORD=password
      - MEDIAWIKI_DB_USER=root
      - MEDIAWIKI_ADMIN_USER=admin
      - MEDIAWIKI_ADMIN_PASS=admin12345
      # uncomment 'MEDIAWIKI_ENABLE_SSL' to enable SSL support
      # - MEDIAWIKI_ENABLE_SSL=true
      - MEDIAWIKI_EXTENSIONS=VisualEditor,WikiEditor,ParserFunctions,Cite,TemplateData,Scribunto,InputBox,Widgets,Maps,Math,LiquidThreads,Variables,RightFunctions,PageInCat,CategoryTree,LabeledSectionTransclusion,UserPageEditProtection,Quiz,UploadWizard,Collection,DynamicPageList,EmbedPage,UWUBCMessages,GoogleAnalyticsMetrics,googleAnalytics,Renameuser,caliper,DeleteBatch,LinkTarget
      - MEDIAWIKI_ALLOW_SITE_CSS_ON_RESTRICTED_PAGES=true
      - RESTBASE_URL=http://nodeservices:7231
      #- LDAP_DOMAIN=CWL
      #- LDAP_SERVER=ldap
      #- LDAP_ENCRYPTION_TYPE=clear
      #- LDAP_SEARCH_ATTRS=cn
      #- LDAP_PROXY_AGENT=cn=admin,dc=example,dc=org
      #- LDAP_PROXY_PASSWORD=admin
      #- LDAP_BASE_DN=dc=example,dc=org
      #- LDAP_USER_BASE_DN=dc=example,dc=org
      #- LDAP_USERNAME_ATTR=cn
      #- LDAP_REALNAME_ATTR=displayname
      #- LDAP_EMAIL_ATTR=mail
      - UBC_AUTH_ENABLED=false
      # FIXME skip domain checking in Parsoid. used in our own ParsoidHandler_custom_xxxx.php.
      # in our Apache conf file, we are redirecting requests to restbase with domain "localhost",
      # but the Parsoid domain is not configurable.  hence disable the check.
      - PARSOID_SKIP_DOAMIN_CHECK=true
      - AUTO_CREATED_USER_REDIRECT=UBC_Wiki:Welcome
      - MEDIAWIKI_MAIN_CACHE=redis
      - MEDIAWIKI_REDIS_HOST=redis
      - MEDIAWIKI_REDIS_PORT=6379
      #- MEDIAWIKI_REDIS_PASSWORD=
      - MEDIAWIKI_REDIS_PERSISTENT=true
      #- MEDIAWIKI_MAIN_CACHE=CACHE_NONE
      #- MEDIAWIKI_MEMCACHED_SERVERS=["memcached:11211"]
      # uncomment to specify the wgUploadPath
      #- MEDIAWIKI_UPLOAD_PATH=/data/upload
      #- GOOGLE_ANALYTICS_UA=UA-XXXXXXX-XX
      # GoogleAnalyticsMetrics: https://www.mediawiki.org/wiki/Extension:GoogleAnalyticsMetrics
      #- GOOGLE_ANALYTICS_METRICS_ALLOWED
      #- GOOGLE_ANALYTICS_METRICS_PATH
      #- GOOGLE_ANALYTICS_METRICS_VIEWID
      - DEBUG=true
      # - CALIPER_HOST=https://caliper.imsglobal.org/caliper/PUT_TEST_BEARER_TOKEN_HERE/message
      # - CALIPER_API_KEY=PUT_TEST_BEARER_TOKEN_HERE
      # - CALIPER_BASE_URL=http://localhost:8888/test_url/
      # - CALIPER_LDAP_ACTOR_HOMEPAGE=http://media_wiki_ldap_homepage
  job_runner:
    <<: *app
    ports: []
    labels:
      org.cookie.container: "mediawiki-runner"
    command: php /var/www/html/maintenance/runJobs.php --wait

  nodeservices:
    image: ubcctlt/mediawiki-node-services:remove_parsoid_js
    environment:
      - MEDIAWIKI_API_URL=http://web/api.php
      - MEDIAWIKI_REST_URL=http://web/rest.php
      - LOG_LEVEL=debug
    volumes:
      - ./data/services:/data
  redis:
    image: redis:6.0-alpine
